name: Extract productVersion

on:
  workflow_dispatch:
  push:
    branches:
      - code-signing

jobs:
  extract-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: |
          version=$(jq -r '.info.productVersion' wails.json)
          echo "version=$version" >> $GITHUB_OUTPUT

  print-version:
    needs: extract-version
    runs-on: ubuntu-latest

    steps:
      - name: Print version
        run: |
          echo ${{ needs.extract-version.outputs.version }}