name: Extract productVersion

on:
  workflow_dispatch:
  push:
    branches:
      - code-signing

jobs:
  extract-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: |
          productVersion=$(jq -r '.info.productVersion' wails.json)
          echo "::set-output name=productVersion::$productVersion"

  print-version:
    needs: extract-version
    runs-on: ubuntu-latest

    steps:
      - name: Print version
        run: |
          echo ${{ needs.extract-version.outputs.productVersion }}